### ISSUE TITLE
Session recording for Ionic apps only shows white/black pages

### ISSUE THREAD

**Issue by samklc** [PostHog/posthog#15109]
## Bug description

Session recording, on normal and V2 (rrweb 2), shows completely unusable screens.

Just created a simple default ionic (on Angular) project with tabs. So you can see the app here: 
https://test-posthog-erf.web.app/

After just clicking on different tabs, here is how the session recording result looks like:
https://user-images.githubusercontent.com/129857723/232476555-444b7ede-e107-4a5e-842a-ad2df5cbbb83.mp4

This has been the same for many of the web browsers and devices. There is no specific web browser/devices that the session recording works well.

## Environment

- [x] PostHog Cloud EU, project ID: [please provide from https://eu.posthog.com/project/settings#1223]

**Comment by benjackwhite** [comment]
Thanks for the report. I don't suppose the source would be available somewhere so that I could fire it up myself and tweak some things to debug? Or is truly just a boilerplate Ionic app?

**Comment by benjackwhite** [comment]
Managed to recreate and noticed that the updated version of rrweb playback much better so should have a fix coming up

**Comment by benjackwhite** [comment]
This should be fixed. If not, feel free to re-open or if there is a different issue, create a new issue 👍

**Comment by samklc** [comment]
@benjackwhite
Sadly the issue is still there and all the recordings are not shown correctly.

I have updated the test project to have a side menu: https://test-posthog-erf.web.app/

The recording sample: https://user-images.githubusercontent.com/129857723/236797729-4662eb6f-9f2b-4d26-8c35-c5f5dae8c4c0.mp4

On the other apps, all the icons of the side menu are shown so big in the middle of the recording covering all the video: 
https://user-images.githubusercontent.com/129857723/236797761-50825d0f-e51d-4492-b0b0-a6ac92032fc9.mp4

Let me know if you need more information.

**Comment by samklc** [comment]
Do I have to create a new issue? @benjackwhite

**Comment by tanuj-g** [comment]
Indeed, I am encountering a similar problem. Initially, when I developed an Android application using React and Capacitor, the session recording functioned perfectly.

However, after incorporating IONIC 7 into the mix, the session recording ceased to work. It only displays a black-and-white screen, as depicted in @samklc's video. I'm experiencing the exact issue, mirroring the troubles @samklc mentioned in their video.

Is there anyone who could provide some guidance or assistance on this matter?

**Comment by RupertBarrow** [comment]
Hi @tanuj-g , did you get this to work ?

**Comment by tanuj-g** [comment]
@RupertBarrow no

**Comment by RupertBarrow** [comment]
Did you get Posthog to work in an Ionic app on mobile ?

**Comment by RupertBarrow** [comment]
I have been trying for days. Posthig in my UInic 8 + Angular 18 app works fine in the web browser, on the mobile Nexus browser on iOS but not in the mobile app tested in TestFlight on iOS.
However, in the same context, I have TrackJS workingvas well as server call-outs.

Could you share how you implemented an initialize Posthog ? Do you get events sent from your iOS app ? What version of Ionic are you using ?

TIA

**Comment by tanuj-g** [comment]
@RupertBarrow 

I am using Ionic 7 with React. 

I followed this implementation 
https://posthog.com/docs/libraries/react

This is my basic initialization

`
posthog.init(KEY, {
    api_host: 'https://app.posthog.com',
    autocapture: false,
    disable_session_recording: true,
    loaded: (posthogInstance) => {
     posthogInstance.startSessionRecording()
    }
  })
`

**Comment by joebnb** [comment]
> [@RupertBarrow](https://github.com/RupertBarrow)
> 
> I am using Ionic 7 with React.
> 
> I followed this implementation https://posthog.com/docs/libraries/react
> 
> This is my basic initialization
> 
> `posthog.init(KEY, { api_host: 'https://app.posthog.com', autocapture: false, disable_session_recording: true, loaded: (posthogInstance) => { posthogInstance.startSessionRecording() } })`

hi did you solve this problem, my project also have this problem with ionic7， i‘m not sure is ionic or posthog problem, at fist i realize that capacitor-http dosent support gzip 

https://github.com/ionic-team/capacitor/pull/6387

when i disable capacitor-http and using native fetch to sending data it's still white screen and tried on web either
