### ISSUE TITLE
HogQL: More helpful error messages

### ISSUE THREAD

**Issue by timgl** [PostHog/posthog#20244]
## Is your feature request related to a problem?

These messages are helpful
![image](https://github.com/PostHog/posthog/assets/1727427/81caddf9-608d-45f3-9ee2-43ad8d8311fa)

This message is not
![image](https://github.com/PostHog/posthog/assets/1727427/6707cf68-a9ef-4db6-af92-2526453611b6)

## Describe the solution you'd like

Return more helpful error messages. I know there are some security concerns here, but perhaps we can limit it to [certain types of error codes](https://clickhouse.com/codebrowser/ClickHouse/src/Common/ErrorCodes.cpp.html) or even have the HogQL parses realise these types of errors? I assume this might be part of the type system? @Gilbert09

**Comment by mariusandra** [comment]
More context: We should add `user_safe=True` to all errors that are safe to show:
https://github.com/PostHog/posthog/blob/cdeb283151af43dced5f7e32ffd31c3967b6e231/posthog/errors.py#L342

We took the safe/cautious approach by default to avoid accidentally leaking anything...

**Comment by Gilbert09** [comment]
I think this is now fixed by @mariusandra here: https://github.com/PostHog/posthog/pull/20292

**Comment by timgl** [comment]
@Gilbert09 I'm still getting this occasionally, where it looks like there are no results but there's actually an error
```sql
select sum(JSONExtractInt(line, 'quantity')) as invoiced_usage, customer_id
, mrr
-- max(tupleElement(period_start, 1)),
-- max(tupleElement(period_end, 1))

from (
select arrayJoin(JSONExtractArrayRaw(JSONExtractString(data, 'lines'), 'data')) as line, customer_id, JSONExtractInt(mrr_per_product, 'session_replay') as mrr, period_start, period_end


from invoice_with_annual
        where JSONExtractInt(mrr_per_product, 'session_replay') > 0
        and toStartOfMonth(tupleElement(period_end, 1)) = toStartOfMonth(now() - toIntervalMonth(1))
        and JSONExtractString(line, 'price', 'nickname') LIKE '%session_replay%'
)
group by customer_id
```

<img width="1276" alt="image" src="https://github.com/PostHog/posthog/assets/1727427/db1cc3ba-6258-4721-90ce-d24341c85473">

**Comment by timgl** [comment]
Another issue. Note the `group by 1`, which isn't allowed and causes an exception in Clickhouse, but doesn't return the error in the API at all.
```sql
select sum(JSONExtractInt(line, 'quantity')) as invoiced_usage, customer_id
, mrr
-- max(tupleElement(period_start, 1)),
-- max(tupleElement(period_end, 1))

from (
select arrayJoin(JSONExtractArrayRaw(JSONExtractString(data, 'lines'), 'data')) as line, customer_id, JSONExtractInt(mrr_per_product, 'session_replay') as mrr, period_start, period_end


from invoice_with_annual
        where JSONExtractInt(mrr_per_product, 'session_replay') > 0
        and toStartOfMonth(tupleElement(period_end, 1)) = toStartOfMonth(now() - toIntervalMonth(1))
        and JSONExtractString(line, 'price', 'nickname') LIKE '%session_replay%'
)
group by 1, customer_id
```

**Comment by mariusandra** [comment]
This simpler query gives me the same non-error locally:

```sql
select toDate(timestamp) as timestamp, count(), event
from events
where {filters} and timestamp <= now()
group by 1, timestamp
order by timestamp asc
limit 100 
```

A fix is here: https://github.com/PostHog/posthog/pull/20611

**Comment by Twixes** [comment]
I think we have this handled for a lot of cases
