### ISSUE TITLE
Filters do nothing with breakdown

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog#2047]
## Bug description

*Please describe.*  
*If this affects the front-end, screenshots would be of great help.*  

In Trends, if I set a filter but then select breakdown, it doesn't breakdown post-filter, it just ignores the filter altogether.

<img width="1440" alt="Screenshot 2020-10-27 at 13 04 21" src="https://user-images.githubusercontent.com/38760734/97305591-35460480-1855-11eb-9975-19010277f386.png">

## Expected behavior

Breakdown + filter should work

## How to reproduce

1. Add filter + breakdown on trends
2. 
3. 

## Additional context

An alternative (temp maybe) would be to clearly show in the UI that the filter isn't applied when breakdown is toggled on. Disabling it or something.

**Comment by EDsCODE** [comment]
It seems this has been addressed as that graph [works](https://app.posthog.com/insights?interval=day&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&breakdown=%24os&breakdown_type=event&properties=%5B%7B%22key%22%3A%22%24os%22%2C%22value%22%3A%22Linux%22%2C%22type%22%3A%22event%22%7D%5D) now

Reopen if it's still a problem/becomes a problem!

**Comment by yakkomajuri** [comment]
Hmm appears some more breakdown problems still exist

<img width="1217" alt="Screenshot 2020-11-24 at 08 44 40" src="https://user-images.githubusercontent.com/38760734/100070121-75d37680-2e31-11eb-9549-cd262b5ec349.png">
