### ISSUE TITLE
Unable to Open Events Page - Cannot read property 'distinct_id'

### ISSUE THREAD

**Issue by Mentioum** [PostHog/posthog#3747]
## Bug description

The /events page shows a white screen when navigating to it.

The console shows multiple of the following error:
```
instrument.js:109 TypeError: Cannot read property 'distinct_id' of null
    at render (EventsTable.js:104)
    at R (index.js:63)
    at $i (react-dom.production.min.js:153)
    at To (react-dom.production.min.js:173)
    at mc (react-dom.production.min.js:265)
    at us (react-dom.production.min.js:246)
    at cs (react-dom.production.min.js:246)
    at Jc (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Da (react-dom.production.min.js:122)
    at Ka (react-dom.production.min.js:123)
    at Wa (react-dom.production.min.js:122)
    at es (react-dom.production.min.js:240)
    at Object.notify (Subscription.js:19)
    at e.t.notifyNestedSubs (Subscription.js:90)
    at e.t.handleChangeWrapper (Subscription.js:95)
    at m (redux.js:221)
    at Object.dispatch (index.esm.js:1176)
    at Object.keys.forEach.e.actions.<computed> [as fetchEventsSuccess] (index.esm.js:287)
    at eventsTableLogic.js:227
    at u (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at n (asyncToGenerator.js:3)
    at c (asyncToGenerator.js:25)
```

I'm not sure how it's possible that I could have got an event into the database without a distinct ID as I'm assuming the API would reject any submissions should it be blank / empty.

## Expected behavior

I would see a list of all of the events

## How to reproduce

1.  Login
2.  Go to Events page
3. (Possibly try to delete and merge some sessions) - heard from marketing team member.

## Environment

- [ x ] PostHog Cloud
- [ ] self-hosted PostHog, version/commit: _please provide_

## Additional context
This did occur after a member of our marketing team tried to delete / merge a particular user from the sessions page but I don't know the exact process they went though.  Would appreciate the help.

**Comment by paolodamico** [comment]
Thanks for reporting @Mentioum! Fix coming out right now.

**Comment by Mentioum** [comment]
Could I ask what happened?

**Comment by paolodamico** [comment]
Absolutely! We merged a PR recently to show more useful information about the person to whom the event is related, but we had some stale code when trying to fetch the person's distinct ID. We haven't converted the events module to Typescript which would've prevented this.

**Comment by Mentioum** [comment]
This is also happening on the Actions page (when editing an action). @paolodamico  I'd opena  new issue but this might actually be easier with the given context above.

**Comment by Mentioum** [comment]
This is also still happening on some 'edit action' pages. @paolodamico
