### ISSUE TITLE
PostHog won't load, endpoints returning 503 error

### ISSUE THREAD

**Issue by dazbradbury** [PostHog/posthog#581]
**Describe the bug**

PostHog seems broken, no pages will load. Dev console gives:

![image](https://user-images.githubusercontent.com/1332601/79237538-2cb45080-7e66-11ea-8e7a-f7c9793a74fb.png)

Homepage shows:

![image](https://user-images.githubusercontent.com/1332601/79237695-5d948580-7e66-11ea-8138-bca1d6724452.png)

**To Reproduce**

Cause unknown, but can reproduce by just going to /events, or the homepage.

It seems the app is responding with a 503 error on those endpoints. 

**Expected behavior**

Pages load.

**Comment by timgl** [comment]
What version are you on/when did you last pull? We did have an issue this morning that we've subsequently fixed, which may have something to do with it.

If not, are there any errors in your console? Maybe if you add the `DEBUG=1` env variable

**Comment by dazbradbury** [comment]
I'm on the latest version of master - looking at the heroku log gives me:

```
2020-04-14T15:09:21+00:00 app[postgres.19774]: [DATABASE] [186-2]  sql_error_code = 00000 STATEMENT:  SELECT DISTINCT ON (keys) jsonb_object_keys("posthog_event"."properties") AS "keys" FROM "posthog_event" WHERE "posthog_event"."team_id" = 1 ORDER BY "keys" ASC
2020-04-14T15:09:21+00:00 app[postgres.19774]: [DATABASE] [187-1]  sql_error_code = 00000 LOG:  duration: 718458.141 ms  statement: SELECT DISTINCT ON (keys) jsonb_object_keys("posthog_event"."properties") AS "keys" FROM "posthog_event" WHERE "posthog_event"."team_id" = 1 ORDER BY "keys" ASC
2020-04-14T15:09:21+00:00 app[postgres.19774]: [DATABASE] [188-1]  sql_error_code = XX000 LOG:  could not send data to client: Connection timed out
```

Suggests the DB is falling over due to the command? It's running on a standard-0 plan. It's worth noting that: 

`SELECT reltuples AS approximate_row_count FROM pg_class WHERE relname = 'posthog_event';`

Returns around 7 million.

I'm also seeing lots of entries as follows:

```
2020-04-14T15:30:08+00:00 app[postgres.20238]: [DATABASE] [137-1]  sql_error_code = 23505 ERROR:  duplicate key value violates unique constraint "unique hash for each team"
2020-04-14T15:30:08+00:00 app[postgres.20238]: [DATABASE] [137-2]  sql_error_code = 23505 DETAIL:  Key (team_id, hash)=(1, 414c039767733a6cb2f4447ab50efb04) already exists.
2020-04-14T15:30:08+00:00 app[postgres.20238]: [DATABASE] [137-3]  sql_error_code = 23505 STATEMENT:  INSERT INTO "posthog_elementgroup" ("team_id", "hash") VALUES (1, '414c039767733a6cb2f4447ab50efb04') RETURNING "posthog_elementgroup"."id"
```

Otherwise, Heroku doesn't seem to give much help on what the issue is, and there isn't an option to restart the database (allthough i have tried restarting the application itself).

**Comment by timgl** [comment]
Just a quick update, when merging the above commits the events table will have an index on timestamp, which will at least allow the events table itself to load. That migration took about a minute to run over 3.5 million events.

We're now working on a slightly bigger refactor to solve those other really long-running queries too.

It's not unlikely we'll run into more of these issues but we're very keen on fixing those so we can support these larger deployments. Keep them coming!

**Comment by dazbradbury** [comment]
Cool - thanks for working on this. 

I've updated to master, but PH still won't load for me. Heroku logs showing:

```
2020-04-15T10:00:48.176948+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=GET path="/api/event/" host=[REDACTED] request_id=8932f8a1-c4c6-425e-8b4f-560d917be3e1 fwd="[REDACTED]" dyno=web.1 connect=0ms service=30002ms status=503 bytes=0 protocol=https


2020-04-15T10:00:48.674484+00:00 app[web.1]: [2020-04-15 10:00:48 +0000] [4] [CRITICAL] WORKER TIMEOUT (pid:46)
2020-04-15T10:00:48.917008+00:00 app[web.2]: [2020-04-15 10:00:48 +0000] [4] [CRITICAL] WORKER TIMEOUT (pid:47)
```

What I'm also finding strange is that I've had posthog disabled on our site (mainly for security reasons as opposed to these bugs), but the heroku worker log is still showing unique key failures trying to insert values:

```
2020-04-15T10:00:57+00:00 app[postgres.26904]: [DATABASE] [34-1]  sql_error_code = 23505 ERROR:  duplicate key value violates unique constraint "unique distinct_id for team"
2020-04-15T10:00:57+00:00 app[postgres.26904]: [DATABASE] [34-2]  sql_error_code = 23505 DETAIL:  Key (team_id, distinct_id)=(1, 2253793) already exists.
2020-04-15T10:00:57+00:00 app[postgres.26904]: [DATABASE] [34-3]  sql_error_code = 23505 STATEMENT:  INSERT INTO "posthog_persondistinctid" ("team_id", "person_id", "distinct_id") VALUES (1, 7468955, '2253793') RETURNING "posthog_persondistinctid"."id"
```

I understand this will happen whilst clients have cached pages with the script, but it's been over 48 hours - so I'm just wondering if the workers are caching events, posting them to the DB is failing, and then they're retrying on loop which may be causing knock on issues.

**Comment by timgl** [comment]
I've merged the migration now so if you merge in master you should be able to run that. It'll still have other issues until we merge #588 though.

We don't use workers (yet!) to store events. Once you run the migration you should at least be able to see where those events are coming from!

In terms of the security, are you talking about #528?

**Comment by timgl** [comment]
@dazbradbury we've merged in those final changes. Let me know if they work and feel free to open more issues if you run into other problems

**Comment by dazbradbury** [comment]
Awesome thanks - yep, Events data all running smoothly and quickly now. 👍 

Am still getting a timeout on the homepage with the default dashboard though (pageviews + popular browsers), and there are still lots of these: `duplicate key value violates unique constraint "unique hash for each team"` errors in the logs.

**Comment by timgl** [comment]
The duplicate key thing is expected -- it's the quickest way to figure out whether we need to insert the distinct ID in the database or not. I should figure out how to silence those errors in the log. It is weird that you're still getting them if you removed it from your site, have you checked what kind of events they are?

The dashboard is another interesting one. We'll probably need some more indexing magic there. Will pick that up next.

**Comment by dazbradbury** [comment]
> It is weird that you're still getting them if you removed it from your site, have you checked what kind of events they are?

Is a full mix. Seems quite a few people keeping very old tabs open and interacting with them. Assume they'll go away once events start disappearing, but thanks for clarifying. 

> The dashboard is another interesting one. We'll probably need some more indexing magic there. Will pick that up next.

Great - thanks! 👍

**Comment by timgl** [comment]
@dazbradbury Hey Daz, we've merged another migration that adds an index and fixes a couple of other small issues. I've tested it with 7m events. We previously used an Action (pageviews) to generate the dashboard items. That doesn't scale too well in this case, so it could be worth removing those items, and recreating them by selecting `$pageview` as an event in /trends.

I think with current master (and your volume and dyno sizes etc) you should be able to do the following things:
1. See the live stream of all events
2. Explore your data in /trends (filtering by properties might be a bit slow, but shouldn't time out)
3. Once you put the JS snippet back, go out and [create an action](https://docs.posthog.com/#/features/actions) on any buttons, links, pageviews that match a specific page
4. See session length/time in /trends

I still expect funnels and paths to fail in your case. I also think it might struggle if you end up putting a bunch more data in and then try to do queries over all time. We will tackle those too in the coming week(s).

Making PostHog work for high volume instances is a very high priority for me (and you're not the only people we're working with with this volume!) so appreciate you sticking with it.

**Comment by dazbradbury** [comment]
@timgl - Thanks will spin up the latest version now and take a look. Much appreciated.

**Comment by dazbradbury** [comment]
@timgl - So now we have everything up and running again, the remaining performance issues seem to be as follows:

**/trends:**

Failed to load resource: the server responded with a status of 503 (Service Unavailable)

![image](https://user-images.githubusercontent.com/1332601/80809241-2c7fb900-8bb9-11ea-9ba6-7d5438539e56.png)

**Dashboard:**

Widgets just keep spinning, plus error message as before due to 503:

![image](https://user-images.githubusercontent.com/1332601/80809333-5afd9400-8bb9-11ea-91ab-1e46de610281.png)


**/events:**

Loads and works pretty smoothly. Main page takes 2.5 seconds to load. 

**/actions**

To be tested properly, but loads pageviews as the default Action ID. 

**/actions/live**

Loads and works

**/people**

Loads, but doesn't seem to be able to handle searching by UserID (app supplied or GUID)

**Summary**

It's still not quire usable with our ever increasing data set. Paths and funnels I haven't tested, as you say you wouldn't expect them to work yet. 

Let me know if I can provide any more info, if it's helpful these are the DB stats:

![image](https://user-images.githubusercontent.com/1332601/80810090-fd6a4700-8bba-11ea-99fc-4cf8d7e4956a.png)

**Comment by EDsCODE** [comment]
@dazbradbury Thanks for continually helping us figure out how to handle high volume deployments!

@timgl @mariusandra Result of some experiments and recreating an environment with 10m events:

**Issue:** The exact issue that's returning the 503 is just a heroku timeout because they have a request timeout of 30seconds.
<img width="1680" alt="Screen Shot 2020-05-03 at 8 24 06 PM" src="https://user-images.githubusercontent.com/13127476/80929823-fee36d00-8d7c-11ea-812c-ccc21acbbebd.png">

**Learnings:** 
Short term adjustments
- An immediate fix and general direction to consider for backend architecture could be to make more endpoints async. We could have the server dispatch the task like we do event processing with celery and return immediately to the client so that requests won't hang and timeout. The return could be discovered by the client through polling or possibly [channels](https://github.com/django/channels). This will prevent timeout errors but query times should be optimized also.
- There are possible adjustments that can be done on the current queries as I haven't closely checked

Involved considerations
- On my test environment, I duplicated the `posthog_event` table but added automatic partitioning by day as suggested [here](https://www.postgresql.org/docs/10/ddl-partitioning.html). This did reduce query times dramatically compared to the current table in certain cases where the query was able to eliminate partitions of days that were outside the filtering range (40s to <10s). However, If the query planned a seq scan on a day with 1m rows, the runtime still suffered so even with partitions. A query across all time would be poor. I will continue looking into this as I may have just overlooked some indexing and conditions that could improve this more
- I considered some sort of roll-up tables. As far as I know, our history of event log doesn't change so rollup tables could be precalculated totals per day but the main problem here is that users have to be able to apply all sorts of filtering and our rollups can't account for all the possible combinations.
- As always, we are also considering a column oriented db like Clickhouse which would help improve our queries as long as we make sure the joins that we need to make are possible (or the values are denormalizable)

**Comment by EDsCODE** [comment]
@dazbradbury Hey Daz, we just added an optimization option for high volume usage! We apply partitions to the event table which should bump query performance. If you check out the latest on master you can follow the new instructions [here](https://github.com/PostHog/posthog.com/pull/45/files) to apply partitions to your table. 

Considering you have several million rows, the update will definitely take some time (took a bit under 10 minutes for 10million events on my instance). Thanks for helping us with this! Let us know how well it works and if any issues come up in the process

**Comment by dazbradbury** [comment]
@EDsCODE - Nice one! 

Not 100% clear on the process for running in these migrations though. I'm set up on Heroku, what's the best way to run in these python commands? Am assuming they need access to the DB / connection strings etc.

**Comment by EDsCODE** [comment]
If you have updated to master, you should be able to use the `heroku run {your command here}` as all the environment settings that are needed should exist in the heroku environment! For example, to apply the multiple event partition example you could do:
`heroku run python manage.py partition --element '$pageview' --element '$autocapture'`.

**Comment by dazbradbury** [comment]
Perfect - FYI just had to change the quotation marks slightly to:

`heroku run python manage.py partition --element "'$pageview'" --element "'$autocapture'"`

Is running in now, will see how I get on once it's all loaded in. Thanks!

**Comment by dazbradbury** [comment]
Perfect - is running in now, will see how I get on once it's all loaded in. Thanks!

**Comment by dazbradbury** [comment]
Looks like PH still falling over for us. Albeit, it looks like the failures have been ongoing for 7 days+ (ie. before upgrade + partitioning), and are impacting data collection as opposed to the dashboard. Hopefully this gives you some insight:

![image](https://user-images.githubusercontent.com/1332601/82042997-bf811e80-96a2-11ea-9e7b-6e3c4b2fd5d4.png)

![image](https://user-images.githubusercontent.com/1332601/82043026-ca3bb380-96a2-11ea-9885-2b0c8f06ee5c.png)
![image](https://user-images.githubusercontent.com/1332601/82043054-d58edf00-96a2-11ea-8cf9-364fa01d6227.png)

![image](https://user-images.githubusercontent.com/1332601/82043068-dc1d5680-96a2-11ea-904d-c4618ade2820.png)

**Comment by timgl** [comment]
@dazbradbury ah, we thought it was just your dashboard falling over due to heavy queries (which should be improved with the partitioning), but it looks like PH is struggling to keep up with all of the events inserts.

Is that screenshot from your web dyno or from your worker dyno?

**Comment by dazbradbury** [comment]
That's the web dyno(s). The worker dyno looks like this (makes me wonder if there is a config issue with the worker being picked up):

![image](https://user-images.githubusercontent.com/1332601/82045586-3fa98300-96a7-11ea-8a28-5f3ff5534086.png)

**Comment by timgl** [comment]
@dazbradbury Just tested this myself, my web worker isn't struggling at all with 100 RPS but the worker falls down (so just needs scaling up), suggesting there is a config error on your deploy somewhere.

Just to check, this is what your dyno formation looks like? 
![image](https://user-images.githubusercontent.com/1727427/82060432-4e9c2f80-96bf-11ea-816a-e7824c82305c.png)

And you don't have a "configuration error" in your app itself?

And Redis is provisioned and running?

**Comment by dazbradbury** [comment]
Current set-up:

![image](https://user-images.githubusercontent.com/1332601/82073068-98414600-96d0-11ea-9d3a-ca8daf137e8e.png)

![image](https://user-images.githubusercontent.com/1332601/82073746-91670300-96d1-11ea-888a-6e97a1290610.png)


I am seeing a configuration error now:

![image](https://user-images.githubusercontent.com/1332601/82073507-3fbe7880-96d1-11ea-8817-93fbee68246d.png)

The whole site is unusably slow now with responses of: 

![image](https://user-images.githubusercontent.com/1332601/82073653-75fbf800-96d1-11ea-89b6-d2466d15960c.png)

Worth noting that there are 20m+ rows in the posthog_element table.
