### ISSUE TITLE
The title of an Insight is sometimes not show an instead a generic "Insight {number}" is shown

### ISSUE THREAD

**Issue by leggetter** [PostHog/posthog#6284]
## Bug description

When loading an insight the expected title is not shown and instead something like the following is shown:

## How to reproduce

1.
2.
3.

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

**Comment by marcushyett-ph** [comment]
cc:@alexkim205

**Comment by mariusandra** [comment]
A lot of changes happened to insights after this issue was posted. @marcushyett-ph was your CC referencing anything?

**Comment by marcushyett-ph** [comment]
Nope not referencing anything specifically.

Since as you say there has been a lot of changes since - I tried to repro it again and I can't make it happen - so I believe it is now resolved.

**Comment by leggetter** [comment]
I'm still seeing insight naming problems with my `release-1.29.0-unstable` deploy.

https://user-images.githubusercontent.com/328367/137787063-1ecf68f7-38be-4f19-804c-6dc489322544.mp4

**Comment by mariusandra** [comment]
This "saved funnels" will be removed very soon when the "saved insights" feature overrides it.

However, bug fixed in https://github.com/PostHog/posthog/pull/6531
