### ISSUE TITLE
Upgrade to 1.30 is failing on Heroku

### ISSUE THREAD

**Issue by avorio** [PostHog/posthog#7408]
## Bug description

I just tried upgrading PostHog from `1.29.1` to `1.30` but got an error instead. It seems to be related to Redis, but the Redis instance is working just fine for the existing installation ... this is what I see in the System Status page:

Metric | Value
-- | --
Redis alive | Yes
Redis version | 5.0.12

## Expected behavior

Seamless upgrade :)

## How to reproduce

1. Pull latest code from GitHub
2. Push code to Heroku
3. Trigger deployment ... and it fails at the Redis connection step

## Environment

- [ ] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [x] self-hosted PostHog (Postgres-based, legacy), version/commit: 1.29.1

## Additional context

```
remote: -----> Python app detected
remote: -----> Using Python version specified in runtime.txt
remote:  !     Python has released a security update! Please consider upgrading to python-3.8.12
remote:        Learn More: https://devcenter.heroku.com/articles/python-runtimes
remote: -----> No change in requirements detected, installing from cache
remote: -----> Using cached install of python-3.8.6
remote: -----> Installing pip 21.3.1, setuptools 57.5.0 and wheel 0.37.0
remote: -----> Installing SQLite3
remote: -----> Installing requirements with pip
remote:        Collecting git+https://github.com/zapier/django-rest-hooks.git@v1.6.0 (from -r /tmp/build_aaefb5ad/requirements.txt (line 75))
remote:          Cloning https://github.com/zapier/django-rest-hooks.git (to revision v1.6.0) to /tmp/pip-req-build-9fyw2e3x
remote:          Running command git clone --filter=blob:none -q https://github.com/zapier/django-rest-hooks.git /tmp/pip-req-build-9fyw2e3x
remote:          Running command git checkout -q d21a070b9a099b5e9c755b2afa6b81c9d8b26e7c
remote:          Resolved https://github.com/zapier/django-rest-hooks.git to commit d21a070b9a099b5e9c755b2afa6b81c9d8b26e7c
remote:          Preparing metadata (setup.py): started
remote:          Preparing metadata (setup.py): finished with status 'done'
remote:        Collecting git+https://github.com/PostHog/infi.clickhouse_orm@f6f4838a75513773696737c9ac37a164af9be632 (from -r /tmp/build_aaefb5ad/requirements.txt (line 117))
remote:          Cloning https://github.com/PostHog/infi.clickhouse_orm (to revision f6f4838a75513773696737c9ac37a164af9be632) to /tmp/pip-req-build-_r2xlefv
remote:          Running command git clone --filter=blob:none -q https://github.com/PostHog/infi.clickhouse_orm /tmp/pip-req-build-_r2xlefv
remote:          Running command git rev-parse -q --verify 'sha^f6f4838a75513773696737c9ac37a164af9be632'
remote:          Running command git fetch -q https://github.com/PostHog/infi.clickhouse_orm f6f4838a75513773696737c9ac37a164af9be632
remote:          Resolved https://github.com/PostHog/infi.clickhouse_orm to commit f6f4838a75513773696737c9ac37a164af9be632
remote:          Preparing metadata (setup.py): started
remote:          Preparing metadata (setup.py): finished with status 'done'
remote: -----> $ python manage.py collectstatic --noinput
remote:        🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻🔻
remote:        Skipping service version requirements. This is dangerous and PostHog might not work as expected!
remote:        🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺🔺
remote:        AXES: BEGIN LOG
remote:        AXES: BEGIN LOG
remote:        AXES: Using django-axes version 5.9.0
remote:        AXES: Using django-axes version 5.9.0
remote:        AXES: blocking by IP only.
remote:        AXES: blocking by IP only.
remote:        1898 static files copied to '/tmp/build_aaefb5ad/staticfiles', 5746 post-processed.
remote: 
remote: -----> Discovering process types
remote:        Procfile declares types -> celeryworker, pluginworker, release, web, worker
remote: 
remote: -----> Compressing...
remote:        Done: 221.6M
remote: -----> Launching...
remote:  !     Release command declared: this new release will not be available until the command succeeds.
remote:        Released v63
remote:        https://XYZ.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
remote: Running release command...
remote: 
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 552, in connect
remote:     sock = self._connect()
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 609, in _connect
remote:     raise err
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 597, in _connect
remote:     sock.connect(socket_address)
remote: ConnectionRefusedError: [Errno 111] Connection refused
remote: 
remote: During handling of the above exception, another exception occurred:
remote: 
remote: Traceback (most recent call last):
remote:   File "manage.py", line 21, in <module>
remote:     main()
remote:   File "manage.py", line 17, in main
remote:     execute_from_command_line(sys.argv)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
remote:     utility.execute()
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
remote:     django.setup()
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
remote:     apps.populate(settings.INSTALLED_APPS)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
remote:     app_config.ready()
remote:   File "/app/posthog/apps.py", line 38, in ready
remote:     [in_range, version] = service_version_requirement.is_service_in_accepted_version()
remote:   File "/app/posthog/version_requirement.py", line 26, in is_service_in_accepted_version
remote:     service_version = self.get_service_version()
remote:   File "/app/posthog/version_requirement.py", line 37, in get_service_version
remote:     return self.get_redis_version()
remote:   File "/app/posthog/version_requirement.py", line 60, in get_redis_version
remote:     version = client.execute_command("INFO")["redis_version"]
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/redis/client.py", line 875, in execute_command
remote:     conn = self.connection or pool.get_connection(command_name, **options)
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 1185, in get_connection
remote:     connection.connect()
remote:   File "/app/.heroku/python/lib/python3.8/site-packages/redis/connection.py", line 557, in connect
remote:     raise ConnectionError(self._error_message(e))
remote: redis.exceptions.ConnectionError: Error 111 connecting to None:6379. Connection refused.
remote: Waiting for release... failed.
To https://git.heroku.com/XYZ.git
   aedb28f12..7d6284715  master -> master
```

**Comment by yakkomajuri** [comment]
@neilkakkar answered to a user with a similar issue on Slack:

> This is suspicious to me O.o
> The release command runs this: https://github.com/PostHog/posthog/blob/master/Procfile#L1
> so, would you mind editing this (for now, just so we can figure whats wrong) - to `REDIS_URL='redis://localhost'` (this should work, since system status shows redis is alive, so I expect you don’t have a custom redis connection URL).

**Comment by avorio** [comment]
Interesting. I hadn't noticed that, thank you.

Why do we need `REDIS_URL='redis://'` in the release?

**Comment by avorio** [comment]
I removed `REDIS_URL='redis://'` from the release command, and it finally succeeded on Heroku.

However, the Plugin server is now down after this upgrade, and I'm seeing these errors on our logs:

```
2021-11-30T18:42:32.772181+00:00 app[worker.1]: yarn run v1.22.17
2021-11-30T18:42:32.858312+00:00 app[worker.1]: $ BASE_DIR=.. node dist/index.js
2021-11-30T18:42:32.953579+00:00 app[worker.1]: node:internal/modules/cjs/loader:936
2021-11-30T18:42:32.953581+00:00 app[worker.1]: throw err;
2021-11-30T18:42:32.953582+00:00 app[worker.1]: ^
2021-11-30T18:42:32.953582+00:00 app[worker.1]: 
2021-11-30T18:42:32.953583+00:00 app[worker.1]: Error: Cannot find module '/app/plugin-server/dist/index.js'
2021-11-30T18:42:32.953583+00:00 app[worker.1]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
2021-11-30T18:42:32.953584+00:00 app[worker.1]: at Function.Module._load (node:internal/modules/cjs/loader:778:27)
2021-11-30T18:42:32.953584+00:00 app[worker.1]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
2021-11-30T18:42:32.953585+00:00 app[worker.1]: at node:internal/main/run_main_module:17:47 {
2021-11-30T18:42:32.953588+00:00 app[worker.1]: code: 'MODULE_NOT_FOUND',
2021-11-30T18:42:32.953589+00:00 app[worker.1]: requireStack: []
2021-11-30T18:42:32.953589+00:00 app[worker.1]: }
2021-11-30T18:42:32.982147+00:00 app[worker.1]: error Command failed with exit code 1.
2021-11-30T18:42:32.982153+00:00 app[worker.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-11-30T18:42:32.996659+00:00 app[worker.1]: 💥 Plugin server crashed!
2021-11-30T18:42:32.996692+00:00 app[worker.1]: ⌛️ Waiting 2 seconds before restarting...
```

Any clues on what might be going on?

**Comment by yakkomajuri** [comment]
Hey @avorio! The solution here is to deploy this branch:

https://github.com/PostHog/posthog/tree/heroku-1.30.0

**Comment by avorio** [comment]
That didn’t work. I’m still seeing this in the logs:

```
2021-12-01T03:17:35.116211+00:00 app[worker.1]: at Function.Module._load (node:internal/modules/cjs/loader:778:27)
2021-12-01T03:17:35.116212+00:00 app[worker.1]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
2021-12-01T03:17:35.116212+00:00 app[worker.1]: at node:internal/main/run_main_module:17:47 {
2021-12-01T03:17:35.116212+00:00 app[worker.1]: code: 'MODULE_NOT_FOUND',
2021-12-01T03:17:35.116213+00:00 app[worker.1]: requireStack: []
2021-12-01T03:17:35.116213+00:00 app[worker.1]: }
2021-12-01T03:17:35.132554+00:00 app[worker.1]: error Command failed with exit code 1.
2021-12-01T03:17:35.132688+00:00 app[worker.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-12-01T03:17:35.140172+00:00 app[worker.1]: 💥 Plugin server crashed!
2021-12-01T03:17:35.140176+00:00 app[worker.1]: ⌛️ Waiting 2 seconds before restarting...
2021-12-01T03:17:37.381025+00:00 app[worker.1]: yarn run v1.22.17
2021-12-01T03:17:37.441665+00:00 app[worker.1]: $ BASE_DIR=.. node dist/index.js
2021-12-01T03:17:37.503754+00:00 app[worker.1]: node:internal/modules/cjs/loader:936
2021-12-01T03:17:37.503758+00:00 app[worker.1]: throw err;
2021-12-01T03:17:37.503758+00:00 app[worker.1]: ^
2021-12-01T03:17:37.503759+00:00 app[worker.1]: 
2021-12-01T03:17:37.503759+00:00 app[worker.1]: Error: Cannot find module '/app/plugin-server/dist/index.js'
2021-12-01T03:17:37.503760+00:00 app[worker.1]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
2021-12-01T03:17:37.503760+00:00 app[worker.1]: at Function.Module._load (node:internal/modules/cjs/loader:778:27)
2021-12-01T03:17:37.503761+00:00 app[worker.1]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
2021-12-01T03:17:37.503761+00:00 app[worker.1]: at node:internal/main/run_main_module:17:47 {
2021-12-01T03:17:37.503762+00:00 app[worker.1]: code: 'MODULE_NOT_FOUND',
2021-12-01T03:17:37.503762+00:00 app[worker.1]: requireStack: []
2021-12-01T03:17:37.503762+00:00 app[worker.1]: }
2021-12-01T03:17:37.521704+00:00 app[worker.1]: error Command failed with exit code 1.
2021-12-01T03:17:37.521862+00:00 app[worker.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-12-01T03:17:37.530872+00:00 app[worker.1]: 💥 Plugin server crashed!
2021-12-01T03:17:37.530877+00:00 app[worker.1]: ⌛️ Waiting 2 seconds before restarting...
2021-12-01T03:17:39.789859+00:00 app[worker.1]: yarn run v1.22.17
2021-12-01T03:17:39.859845+00:00 app[worker.1]: $ BASE_DIR=.. node dist/index.js
2021-12-01T03:17:39.924950+00:00 app[worker.1]: node:internal/modules/cjs/loader:936
2021-12-01T03:17:39.924952+00:00 app[worker.1]: throw err;
2021-12-01T03:17:39.924953+00:00 app[worker.1]: ^
2021-12-01T03:17:39.924953+00:00 app[worker.1]: 
2021-12-01T03:17:39.924954+00:00 app[worker.1]: Error: Cannot find module '/app/plugin-server/dist/index.js'
2021-12-01T03:17:39.924955+00:00 app[worker.1]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
2021-12-01T03:17:39.924955+00:00 app[worker.1]: at Function.Module._load (node:internal/modules/cjs/loader:778:27)
2021-12-01T03:17:39.924955+00:00 app[worker.1]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
2021-12-01T03:17:39.924956+00:00 app[worker.1]: at node:internal/main/run_main_module:17:47 {
2021-12-01T03:17:39.924956+00:00 app[worker.1]: code: 'MODULE_NOT_FOUND',
2021-12-01T03:17:39.924959+00:00 app[worker.1]: requireStack: []
2021-12-01T03:17:39.924959+00:00 app[worker.1]: }
2021-12-01T03:17:39.943701+00:00 app[worker.1]: error Command failed with exit code 1.
2021-12-01T03:17:39.944066+00:00 app[worker.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2021-12-01T03:17:39.953267+00:00 app[worker.1]: 💥 Plugin server crashed!
2021-12-01T03:17:39.953271+00:00 app[worker.1]: ⌛️ Waiting 2 seconds before restarting...
2021-12-01T03:17:42.258057+00:00 app[worker.1]: yarn run v1.22.17
2021-12-01T03:17:42.328495+00:00 app[worker.1]: $ BASE_DIR=.. node dist/index.js
2021-12-01T03:17:42.392765+00:00 app[worker.1]: node:internal/modules/cjs/loader:936
2021-12-01T03:17:42.392767+00:00 app[worker.1]: throw err;
2021-12-01T03:17:42.392767+00:00 app[worker.1]: ^
```

**Comment by yakkomajuri** [comment]
I pushed a final commit, that should do it! 

Feel free to reopen if not

**Comment by avk** [comment]
I'm still seeing similar errors today after deploying *heroku-1.30.0*:

```
2022-01-15T19:25:04.861970+00:00 app[worker.1]: 
2022-01-15T19:25:04.861971+00:00 app[worker.1]: Error: Cannot find module '/app/plugin-server/dist/index.js'
2022-01-15T19:25:04.861971+00:00 app[worker.1]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
2022-01-15T19:25:04.861972+00:00 app[worker.1]: at Function.Module._load (node:internal/modules/cjs/loader:778:27)
2022-01-15T19:25:04.861972+00:00 app[worker.1]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
2022-01-15T19:25:04.861973+00:00 app[worker.1]: at node:internal/main/run_main_module:17:47 {
2022-01-15T19:25:04.861973+00:00 app[worker.1]: code: 'MODULE_NOT_FOUND',
2022-01-15T19:25:04.861973+00:00 app[worker.1]: requireStack: []
2022-01-15T19:25:04.861974+00:00 app[worker.1]: }
2022-01-15T19:25:04.877782+00:00 app[worker.1]: error Command failed with exit code 1.
2022-01-15T19:25:04.877919+00:00 app[worker.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2022-01-15T19:25:04.898771+00:00 app[worker.1]: 💥 Plugin server crashed!
2022-01-15T19:25:04.898773+00:00 app[worker.1]: ⌛️ Waiting 2 seconds before restarting...
2022-01-15T19:25:07.145324+00:00 app[worker.1]: yarn run v1.22.17
2022-01-15T19:25:07.205189+00:00 app[worker.1]: $ BASE_DIR=.. node dist/index.js
2022-01-15T19:25:07.255491+00:00 app[worker.1]: node:internal/modules/cjs/loader:936
2022-01-15T19:25:07.255493+00:00 app[worker.1]: throw err;
2022-01-15T19:25:07.255493+00:00 app[worker.1]: ^
2022-01-15T19:25:07.255494+00:00 app[worker.1]: 
2022-01-15T19:25:07.255494+00:00 app[worker.1]: Error: Cannot find module '/app/plugin-server/dist/index.js'
2022-01-15T19:25:07.255495+00:00 app[worker.1]: at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
2022-01-15T19:25:07.255496+00:00 app[worker.1]: at Function.Module._load (node:internal/modules/cjs/loader:778:27)
2022-01-15T19:25:07.255496+00:00 app[worker.1]: at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
2022-01-15T19:25:07.255497+00:00 app[worker.1]: at node:internal/main/run_main_module:17:47 {
2022-01-15T19:25:07.255497+00:00 app[worker.1]: code: 'MODULE_NOT_FOUND',
2022-01-15T19:25:07.255497+00:00 app[worker.1]: requireStack: []
2022-01-15T19:25:07.255498+00:00 app[worker.1]: }
2022-01-15T19:25:07.271268+00:00 app[worker.1]: error Command failed with exit code 1.
2022-01-15T19:25:07.271504+00:00 app[worker.1]: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2022-01-15T19:25:07.280659+00:00 app[worker.1]: 💥 Plugin server crashed!
2022-01-15T19:25:07.280664+00:00 app[worker.1]: ⌛️ Waiting 2 seconds before restarting...
2022-01-15T19:25:09.557806+00:00 app[worker.1]: yarn run v1.22.17
2022-01-15T19:25:09.621669+00:00 app[worker.1]: $ BASE_DIR=.. node dist/index.js
2022-01-15T19:25:09.690095+00:00 app[worker.1]: node:internal/modules/cjs/loader:936
2022-01-15T19:25:09.690096+00:00 app[worker.1]: throw err;
2022-01-15T19:25:09.690097+00:00 app[worker.1]: ^
2022-01-15T19:25:09.690097+00:00 app[worker.1]: 
```

**Comment by avk** [comment]
And I made sure to deploy the latest commit, [ec31ea6](https://github.com/PostHog/posthog/commit/ec31ea6055ce00210319e569b0971d697191446b), from [heroku-1.30.0](https://github.com/PostHog/posthog/tree/heroku-1.30.0).

**Comment by yakkomajuri** [comment]
Hey @avk ! What commands did you use to deploy? Also was this a _new_ deploy or an upgrade? What's the Node.js version on the server?

**Comment by avk** [comment]
I deployed to Heroku via: `git push -f heroku origin/heroku-1.30.0:master`

`node --version`
v16.13.2

**Comment by avk** [comment]
I got what I needed from 1.29.1 on Heroku, so I'm stopping my efforts to upgrade further. Thanks.
