### ISSUE TITLE
Can not select "yesterday" in chart without also getting "today"

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog#7820]
## Bug description

Currently 9am on the 22nd of December in Belgium. When selecting "yesterday", I also see most of today in the chart:

![2021-12-22 09 09 27](https://user-images.githubusercontent.com/53387/147058198-dd20be99-1bc1-4104-8e1a-f50dd066f1f6.gif)

## Expected behavior

I expect yesterday to result in a point on yesterday, and today to result in today... Even if we're messed up with the timezones, there should still be just one point no matter which day I select

## How to reproduce

1. Go to trends or funnels
2. Select today & yesterday & explicitly select yesterday's dates
3. Watch the numbers no line up

## Environment

- [x] PostHog Cloud
- [ ] self-hosted PostHog (ClickHouse-based), version/commit: _please provide_
- [ ] self-hosted PostHog (Postgres-based, legacy), version/commit: _please provide_

## Additional context

Came from a customer report in Slack.

**Comment by sgsurefit931** [comment]
Hey, when can this issue be resolved?

**Comment by paolodamico** [comment]
Hey @sgsurefit931! We're reviewing this internally, we'll try to issue a fix soon

**Comment by paolodamico** [comment]
Fixed in #7911, FYI @sgsurefit931

**Comment by sgsurefit931** [comment]
Hey, I can still see the discrepancies while selecting date-range vs yesterday. Eg: yesterday was 01-05-2022, so I selected "Yesterday" to see 214 users on landing page vs when I selected "date-range" 01-05-2022 to 01-05-2022, I got 92 users on landing page. This is funnel I am talking about. @paolodamico

**Comment by paolodamico** [comment]
@sgsurefit931 can you link the insight you're referring too and/or upload screenshots? I've tested internally and haven't been able to reproduce

**Comment by sgsurefit931** [comment]
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/71784878/148435467-b3cb272f-3c7f-46d2-b6a2-20f3d92f0dd5.png">

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/71784878/148435557-93695b53-7769-43fd-a243-5f6c351d6d45.png">

**Comment by paolodamico** [comment]
From your screenshot looks like you're comparing "Yesterday" to today (as today is Jan 6)

**Comment by sgsurefit931** [comment]
Hey, in my time zone it's Jan 7(Please see top right of screen shot). I also asked my colleague to check in PT time zone. She also reported same discrepancy. If you want I can ask her to send screen shots of her timezone.

**Comment by paolodamico** [comment]
All insights in PostHog are UTC, so "Yesterday" means the day before in UTC (in this case Jan 5, as it's ~19:30 in UTC). Can you check if setting the date range Jan 5 - Jan 5 works as expected please?

**Comment by sgsurefit931** [comment]
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/71784878/148441011-f761c13f-dad6-4b93-8021-fea54634893d.png">

**Comment by sgsurefit931** [comment]
This time I got 128 users.

**Comment by paolodamico** [comment]
Just one more thing, can you try refreshing both the "Yesterday" and "2021-01-05" (well now 2021-01-06 as it's already Jan 7th on UTC). CC @neilkakkar @EDsCODE could you help us out here?

**Comment by EDsCODE** [comment]
+1 To @paolodamico. Please try refreshing once you have your filters set. The caching can be misleading as you might be expecting the same results with different filters that mean the same time range but they've been cached at different points in time

**Comment by sgsurefit931** [comment]
Okay, I think I am getting correct results in my timezone. Let me also confirm with my colleague and get back to you.
