### ISSUE TITLE
Annotations aren't plotting correctly on graphs with lots of plots

### ISSUE THREAD

**Issue by corywatilo** [PostHog/posthog#7841]
## Bug description

It appears that when there are a lot of dates plotted, the annotations don't display correctly.

![2021-12-25 08 12 13](https://user-images.githubusercontent.com/154479/147388053-f9770544-1fdc-4013-91fa-ad14a9dcb659.gif)

## How to reproduce

1. See on [internal insight](https://app.posthog.com/insights/KWD9W8f7/edit?insight=TRENDS&display=ActionsLineGraph&interval=month&actions=%5B%5D&events=%5B%7B%22id%22%3A%22%24pageview%22%2C%22name%22%3A%22%24pageview%22%2C%22type%22%3A%22events%22%2C%22order%22%3A0%7D%5D&filter_test_accounts=true&properties=%5B%7B%22key%22%3A%22%24current_url%22%2C%22value%22%3A%5B%22https%3A%2F%2Fposthog.com%2Fdocs%2Fuser-guides%2Fcohorts%22%5D%2C%22operator%22%3A%22exact%22%2C%22type%22%3A%22event%22%7D%5D&date_from=all&compare=false)

## Environment

- [X] PostHog Cloud

**Comment by mariusandra** [comment]
I think this is fixed @corywatilo ? I experienced this previously as well, but only with the `line-graph-v2` flag turned on. This works for me now, no matter if the flag is on or off.

**Comment by Twixes** [comment]
It is only a thing with `line-graph-v2` (which only beta users see), but I'm still experiencing this.
![Annotations off the chart](https://user-images.githubusercontent.com/4550621/148740144-052d58ec-3f15-46c1-85e7-37a6361685a5.png)

**Comment by jamesefhawkins** [comment]
I've same issue as @Twixes (on [this dashboard](https://app.posthog.com/dashboard/2973))
